package com.mrtien.autoskip;

import android.accessibilityservice.AccessibilityService;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.PixelFormat;
import android.graphics.Rect;
import android.graphics.drawable.GradientDrawable;
import android.os.Handler;
import android.os.Looper;
import android.os.SystemClock;
import android.view.Gravity;
import android.view.WindowManager;
import android.view.accessibility.AccessibilityEvent;
import android.view.accessibility.AccessibilityNodeInfo;
import android.view.accessibility.AccessibilityWindowInfo;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import java.util.ArrayDeque;
import java.util.List;
import java.util.Locale;

/**
 * v2.2.1 - passive iOS-like paste menu.
 *
 * The service NEVER places a touch-catching overlay over an input field and NEVER
 * re-injects taps. All taps, double taps, long presses and selections remain 100%
 * native to the foreground app. We only observe accessibility events after Android
 * has processed the touch.
 *
 * This is important because an accessibility overlay over EditText breaks native
 * double-tap word selection on many apps and makes a two-tap gesture require a
 * third tap. The passive detector groups focus/click/selection events from the same
 * editable and shows a very small DÁN + history menu without covering the field.
 */
public class AdPasteAccessibilityService extends AccessibilityService {

    private static final long DOUBLE_TAP_MIN_MS = 90L;
    private static final long DOUBLE_TAP_MAX_MS = 720L;
    private static final long SAME_TOUCH_EVENT_DEBOUNCE_MS = 95L;
    private static final long TEXT_CHANGE_GUARD_MS = 260L;
    private static final long MENU_TIMEOUT_MS = 4600L;

    private final Handler handler = new Handler(Looper.getMainLooper());
    private WindowManager windowManager;
    private ClipboardManager clipboardManager;

    private LinearLayout pasteMenu;
    private ViewHolder historyHolder;
    private AccessibilityNodeInfo menuTarget;
    private String menuTargetSignature = "";
    private final Rect menuTargetBounds = new Rect();

    private String lastForegroundPackage = "";
    private String lastSelectedText = "";
    private long lastSelectedAt;
    private long lastTextChangedAt;

    // Passive physical-tap approximation. Several accessibility events generated by
    // one real tap are de-duplicated, then two distinct clusters count as double tap.
    private long lastSignalAt;
    private String lastSignalSignature = "";
    private long firstTapAt;
    private String firstTapSignature = "";

    private final Runnable hideMenusRunnable = () -> {
        hidePasteMenu();
        hideHistoryPanel();
    };

    private final ClipboardManager.OnPrimaryClipChangedListener clipboardListener =
            () -> handler.postDelayed(this::captureCurrentClipboardBestEffort, 100L);

    @Override
    protected void onServiceConnected() {
        super.onServiceConnected();
        windowManager = (WindowManager) getSystemService(WINDOW_SERVICE);
        clipboardManager = (ClipboardManager) getSystemService(CLIPBOARD_SERVICE);
        if (clipboardManager != null) {
            try {
                clipboardManager.addPrimaryClipChangedListener(clipboardListener);
            } catch (Throwable ignored) {
            }
        }
        if (ShizukuClipboardBridge.hasPermission()) {
            ShizukuClipboardBridge.start(this);
        }
        resetTapDetector();
    }

    @Override
    public void onAccessibilityEvent(AccessibilityEvent event) {
        if (event == null) return;

        String pkg = event.getPackageName() == null ? "" : event.getPackageName().toString();
        if (!pkg.isEmpty()) lastForegroundPackage = pkg;

        int type = event.getEventType();

        // Keep clipboard-history fallback independent of the paste shortcut switch.
        if (type == AccessibilityEvent.TYPE_VIEW_TEXT_SELECTION_CHANGED) {
            rememberSelectedText(event.getSource());
        }
        if (type == AccessibilityEvent.TYPE_VIEW_CLICKED) {
            String label = nodeLabel(event.getSource());
            if (isCopyLabel(label)) {
                if (!lastSelectedText.isEmpty()
                        && SystemClock.elapsedRealtime() - lastSelectedAt < 10000L) {
                    ClipboardHistoryStore.addText(this, lastSelectedText);
                }
                handler.postDelayed(this::captureCurrentClipboardBestEffort, 120L);
            }
        }

        if (!isDoubleTapPasteEnabled()) {
            hidePasteMenu();
            hideHistoryPanel();
            resetTapDetector();
            return;
        }

        if (getPackageName().equals(pkg)) return;

        if (type == AccessibilityEvent.TYPE_WINDOW_STATE_CHANGED
                || type == AccessibilityEvent.TYPE_WINDOWS_CHANGED) {
            hidePasteMenu();
            hideHistoryPanel();
            resetTapDetector();
            return;
        }

        if (type == AccessibilityEvent.TYPE_VIEW_TEXT_CHANGED) {
            lastTextChangedAt = SystemClock.elapsedRealtime();
            hidePasteMenu();
            hideHistoryPanel();
            resetTapDetector();
            return;
        }

        if (type != AccessibilityEvent.TYPE_VIEW_FOCUSED
                && type != AccessibilityEvent.TYPE_VIEW_CLICKED
                && type != AccessibilityEvent.TYPE_VIEW_TEXT_SELECTION_CHANGED) {
            return;
        }

        AccessibilityNodeInfo editable = resolveEditableForEvent(event);
        if (!isEditableNode(editable) || editable.isPassword()) return;

        String editablePkg = editable.getPackageName() == null
                ? pkg : editable.getPackageName().toString();
        if (getPackageName().equals(editablePkg)) return;

        String signature = nodeSignature(editable, editablePkg);

        if (type == AccessibilityEvent.TYPE_VIEW_TEXT_SELECTION_CHANGED) {
            // Typing on MagicOS can emit a selection event for every character.
            if (SystemClock.elapsedRealtime() - lastTextChangedAt < TEXT_CHANGE_GUARD_MS) {
                return;
            }

            int start = editable.getTextSelectionStart();
            int end = editable.getTextSelectionEnd();

            // A normal Android double-tap on existing text selects a word/range.
            // Do NOT alter selection. Just add our tiny menu after the native action.
            if (start >= 0 && end >= 0 && start != end) {
                resetTapDetector();
                showPasteMenu(editable, signature);
                return;
            }
        }

        registerInteractionSignal(editable, signature);
    }

    private void registerInteractionSignal(AccessibilityNodeInfo editable, String signature) {
        long now = SystemClock.elapsedRealtime();

        // One physical tap often produces FOCUSED + CLICKED + SELECTION_CHANGED.
        // Collapse events that arrive almost at the same time into one tap.
        if (signature.equals(lastSignalSignature)
                && now - lastSignalAt >= 0L
                && now - lastSignalAt < SAME_TOUCH_EVENT_DEBOUNCE_MS) {
            return;
        }

        lastSignalAt = now;
        lastSignalSignature = signature;

        long delta = now - firstTapAt;
        if (signature.equals(firstTapSignature)
                && firstTapAt > 0L
                && delta >= DOUBLE_TAP_MIN_MS
                && delta <= DOUBLE_TAP_MAX_MS) {
            resetTapDetector();
            showPasteMenu(editable, signature);
            return;
        }

        firstTapAt = now;
        firstTapSignature = signature;
    }

    private AccessibilityNodeInfo resolveEditableForEvent(AccessibilityEvent event) {
        AccessibilityNodeInfo source = event.getSource();
        AccessibilityNodeInfo editable = findEditableAncestor(source);
        if (editable != null) return editable;
        return findFocusedEditableInWindows();
    }

    private AccessibilityNodeInfo findEditableAncestor(AccessibilityNodeInfo node) {
        AccessibilityNodeInfo current = node;
        for (int depth = 0; current != null && depth < 7; depth++) {
            if (isEditableNode(current)) return current;
            current = current.getParent();
        }
        return null;
    }

    private void showPasteMenu(AccessibilityNodeInfo target, String signature) {
        if (windowManager == null || target == null) return;

        hidePasteMenu();
        hideHistoryPanel();
        captureCurrentClipboardBestEffort();

        try {
            menuTarget = AccessibilityNodeInfo.obtain(target);
        } catch (Throwable t) {
            menuTarget = target;
        }
        menuTargetSignature = signature;
        target.getBoundsInScreen(menuTargetBounds);
        if (menuTargetBounds.isEmpty()) return;

        LinearLayout bar = new LinearLayout(this);
        bar.setOrientation(LinearLayout.HORIZONTAL);
        bar.setGravity(Gravity.CENTER_VERTICAL);
        bar.setPadding(dp(2), dp(1), dp(2), dp(1));

        GradientDrawable bg = new GradientDrawable();
        bg.setColor(Color.rgb(38, 38, 38));
        bg.setCornerRadius(dp(9));
        bar.setBackground(bg);
        bar.setElevation(dp(7));

        TextView paste = menuButton("DÁN", 13f);
        paste.setOnClickListener(v -> pasteLatest());
        bar.addView(paste, new LinearLayout.LayoutParams(dp(52), dp(32)));

        TextView history = menuButton("▤", 17f);
        history.setContentDescription("Lịch sử sao chép");
        history.setOnClickListener(v -> showHistoryPanel());
        bar.addView(history, new LinearLayout.LayoutParams(dp(34), dp(32)));

        pasteMenu = bar;

        int menuW = dp(90);
        int menuH = dp(34);
        int[] pos = menuPositionOutsideField(menuTargetBounds, menuW, menuH);
        WindowManager.LayoutParams lp = overlayParams(
                WindowManager.LayoutParams.WRAP_CONTENT,
                WindowManager.LayoutParams.WRAP_CONTENT,
                pos[0],
                pos[1]
        );

        try {
            windowManager.addView(bar, lp);
            handler.removeCallbacks(hideMenusRunnable);
            handler.postDelayed(hideMenusRunnable, MENU_TIMEOUT_MS);
        } catch (Throwable t) {
            pasteMenu = null;
        }
    }

    private TextView menuButton(String label, float sp) {
        TextView t = new TextView(this);
        t.setText(label);
        t.setTextColor(Color.WHITE);
        t.setTextSize(sp);
        t.setGravity(Gravity.CENTER);
        t.setPadding(dp(4), 0, dp(4), 0);
        return t;
    }

    private void pasteLatest() {
        boolean ok = performPasteOnTarget();
        if (ok) incrementPasteCount();
        else Toast.makeText(this, "Ô này không cho phép Dán tự động.", Toast.LENGTH_SHORT).show();
        hidePasteMenu();
        hideHistoryPanel();
        resetTapDetector();
    }

    private void showHistoryPanel() {
        captureCurrentClipboardBestEffort();
        hideHistoryPanel();
        List<ClipboardHistoryStore.Item> items = ClipboardHistoryStore.load(this);
        if (items.isEmpty()) {
            Toast.makeText(this, "Chưa có lịch sử sao chép.", Toast.LENGTH_SHORT).show();
            return;
        }

        LinearLayout root = new LinearLayout(this);
        root.setOrientation(LinearLayout.VERTICAL);
        root.setPadding(dp(7), dp(7), dp(7), dp(7));
        GradientDrawable bg = new GradientDrawable();
        bg.setColor(Color.rgb(42, 42, 42));
        bg.setCornerRadius(dp(14));
        root.setBackground(bg);
        root.setElevation(dp(10));

        TextView title = menuButton("LỊCH SỬ SAO CHÉP   ✕", 14f);
        title.setGravity(Gravity.START | Gravity.CENTER_VERTICAL);
        title.setOnClickListener(v -> {
            hideHistoryPanel();
            handler.removeCallbacks(hideMenusRunnable);
            handler.postDelayed(hideMenusRunnable, MENU_TIMEOUT_MS);
        });
        root.addView(title, new LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT, dp(38)));

        ScrollView scroll = new ScrollView(this);
        LinearLayout list = new LinearLayout(this);
        list.setOrientation(LinearLayout.VERTICAL);
        scroll.addView(list);

        int count = Math.min(items.size(), 30);
        for (int i = 0; i < count; i++) {
            ClipboardHistoryStore.Item item = items.get(i);
            TextView row = new TextView(this);
            row.setText(item.preview());
            row.setTextColor(Color.WHITE);
            row.setTextSize(14f);
            row.setPadding(dp(11), dp(10), dp(11), dp(10));
            GradientDrawable rowBg = new GradientDrawable();
            rowBg.setColor(i % 2 == 0 ? Color.rgb(56, 56, 56) : Color.rgb(49, 49, 49));
            rowBg.setCornerRadius(dp(8));
            row.setBackground(rowBg);
            LinearLayout.LayoutParams rp = new LinearLayout.LayoutParams(
                    LinearLayout.LayoutParams.MATCH_PARENT,
                    LinearLayout.LayoutParams.WRAP_CONTENT
            );
            rp.bottomMargin = dp(4);
            list.addView(row, rp);
            row.setOnClickListener(v -> pasteHistoryItem(item));
        }

        root.addView(scroll, new LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT, dp(250)));

        ViewHolder holder = new ViewHolder();
        holder.view = root;
        historyHolder = holder;

        int screenW = getResources().getDisplayMetrics().widthPixels;
        int screenH = getResources().getDisplayMetrics().heightPixels;
        int width = Math.min(dp(350), screenW - dp(20));
        int height = dp(304);
        int x = Math.max(dp(10), Math.min(menuTargetBounds.left, screenW - width - dp(10)));
        int y = menuTargetBounds.top - height - dp(8);
        if (y < dp(10)) {
            y = Math.min(menuTargetBounds.bottom + dp(8), screenH - height - dp(10));
        }

        WindowManager.LayoutParams lp = overlayParams(width, height, x, y);
        try {
            windowManager.addView(root, lp);
            handler.removeCallbacks(hideMenusRunnable);
            handler.postDelayed(hideMenusRunnable, 12000L);
        } catch (Throwable t) {
            historyHolder = null;
        }
    }

    private void pasteHistoryItem(ClipboardHistoryStore.Item item) {
        ClipData clip = ClipboardHistoryStore.toClipData(this, item);
        if (clip == null || clipboardManager == null) {
            Toast.makeText(this, "Mục lịch sử này không còn dùng được.", Toast.LENGTH_SHORT).show();
            return;
        }
        try {
            clipboardManager.setPrimaryClip(clip);
        } catch (Throwable t) {
            Toast.makeText(this, "Không thể đưa mục này vào clipboard.", Toast.LENGTH_SHORT).show();
            return;
        }

        hideHistoryPanel();
        handler.postDelayed(() -> {
            if (performPasteOnTarget()) incrementPasteCount();
            else Toast.makeText(this, "Ứng dụng này không nhận kiểu nội dung đã chọn.", Toast.LENGTH_SHORT).show();
            hidePasteMenu();
            resetTapDetector();
        }, 100L);
    }

    private boolean performPasteOnTarget() {
        AccessibilityNodeInfo target = findFocusedEditableInWindows();
        if (target == null || !isEditableNode(target)) target = menuTarget;
        if (target == null) target = findEditableBySignature(menuTargetSignature);
        if (target == null) return false;

        try {
            target.performAction(AccessibilityNodeInfo.ACTION_FOCUS);
            if (target.performAction(AccessibilityNodeInfo.ACTION_PASTE)) return true;
        } catch (Throwable ignored) {
        }

        // Text-only fallback for apps that expose SET_TEXT but not PASTE.
        return pasteTextWithSetText(target);
    }

    private boolean pasteTextWithSetText(AccessibilityNodeInfo target) {
        if (target == null || clipboardManager == null) return false;
        try {
            ClipData clip = clipboardManager.getPrimaryClip();
            if (clip == null || clip.getItemCount() == 0) return false;
            CharSequence inserted = clip.getItemAt(0).coerceToText(this);
            if (inserted == null) return false;

            String old = target.getText() == null ? "" : target.getText().toString();
            int start = target.getTextSelectionStart();
            int end = target.getTextSelectionEnd();
            if (start < 0 || start > old.length()) start = old.length();
            if (end < 0 || end > old.length()) end = start;
            if (end < start) {
                int tmp = start;
                start = end;
                end = tmp;
            }

            String value = old.substring(0, start) + inserted + old.substring(end);
            android.os.Bundle args = new android.os.Bundle();
            args.putCharSequence(
                    AccessibilityNodeInfo.ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE,
                    value
            );
            return target.performAction(AccessibilityNodeInfo.ACTION_SET_TEXT, args);
        } catch (Throwable ignored) {
            return false;
        }
    }

    private void captureCurrentClipboardBestEffort() {
        ClipData clip = null;
        if (ShizukuClipboardBridge.hasPermission()) {
            if (!ShizukuClipboardBridge.isRunning()) ShizukuClipboardBridge.start(this);
            clip = ShizukuClipboardBridge.readNow();
        }
        if (clip == null && clipboardManager != null) {
            try {
                clip = clipboardManager.getPrimaryClip();
            } catch (Throwable ignored) {
            }
        }
        if (clip != null) ClipboardHistoryStore.addClip(this, clip);
    }

    private void rememberSelectedText(AccessibilityNodeInfo node) {
        if (node == null || node.getText() == null) return;
        try {
            int start = node.getTextSelectionStart();
            int end = node.getTextSelectionEnd();
            String text = node.getText().toString();
            if (start >= 0 && end > start && end <= text.length()) {
                lastSelectedText = text.substring(start, end);
                lastSelectedAt = SystemClock.elapsedRealtime();
            }
        } catch (Throwable ignored) {
        }
    }

    private String nodeLabel(AccessibilityNodeInfo node) {
        if (node == null) return "";
        CharSequence text = node.getText();
        if (text == null || text.length() == 0) text = node.getContentDescription();
        return text == null ? "" : text.toString().trim().toLowerCase(Locale.ROOT);
    }

    private boolean isCopyLabel(String label) {
        if (label == null) return false;
        return "copy".equals(label)
                || "sao chép".equals(label)
                || "sao chep".equals(label);
    }

    private AccessibilityNodeInfo findFocusedEditableInWindows() {
        try {
            List<AccessibilityWindowInfo> windows = getWindows();
            if (windows != null) {
                for (int i = windows.size() - 1; i >= 0; i--) {
                    AccessibilityWindowInfo w = windows.get(i);
                    if (w == null) continue;
                    AccessibilityNodeInfo root = w.getRoot();
                    if (root == null) continue;
                    AccessibilityNodeInfo focused = root.findFocus(AccessibilityNodeInfo.FOCUS_INPUT);
                    if (isEditableNode(focused)) return focused;
                }
            }
        } catch (Throwable ignored) {
        }

        try {
            AccessibilityNodeInfo root = getRootInActiveWindow();
            if (root != null) {
                AccessibilityNodeInfo focused = root.findFocus(AccessibilityNodeInfo.FOCUS_INPUT);
                if (isEditableNode(focused)) return focused;
            }
        } catch (Throwable ignored) {
        }
        return null;
    }

    private boolean isEditableNode(AccessibilityNodeInfo node) {
        if (node == null || !node.isVisibleToUser() || !node.isEnabled()) return false;
        if (node.isPassword()) return false;
        if (node.isEditable()) return true;

        CharSequence cls = node.getClassName();
        if (cls != null) {
            String c = cls.toString().toLowerCase(Locale.ROOT);
            if (c.contains("edittext") || c.contains("textfield") || c.contains("searchview")) {
                return true;
            }
        }

        try {
            for (AccessibilityNodeInfo.AccessibilityAction action : node.getActionList()) {
                if (action.getId() == AccessibilityNodeInfo.ACTION_SET_TEXT
                        || action.getId() == AccessibilityNodeInfo.ACTION_PASTE) {
                    return true;
                }
            }
        } catch (Throwable ignored) {
        }
        return false;
    }

    private String nodeSignature(AccessibilityNodeInfo node, String fallbackPackage) {
        Rect r = new Rect();
        node.getBoundsInScreen(r);
        String pkg = node.getPackageName() == null
                ? fallbackPackage : node.getPackageName().toString();
        String id = node.getViewIdResourceName();
        String cls = node.getClassName() == null ? "" : node.getClassName().toString();
        return pkg + "|" + (id == null ? "" : id) + "|" + cls + "|" + r.flattenToString();
    }

    private AccessibilityNodeInfo findEditableBySignature(String signature) {
        if (signature == null || signature.isEmpty()) return null;
        try {
            List<AccessibilityWindowInfo> windows = getWindows();
            if (windows != null) {
                for (AccessibilityWindowInfo w : windows) {
                    if (w == null) continue;
                    AccessibilityNodeInfo found = findEditableBySignature(w.getRoot(), signature);
                    if (found != null) return found;
                }
            }
        } catch (Throwable ignored) {
        }
        return findEditableBySignature(getRootInActiveWindow(), signature);
    }

    private AccessibilityNodeInfo findEditableBySignature(
            AccessibilityNodeInfo root,
            String signature
    ) {
        if (root == null) return null;
        ArrayDeque<AccessibilityNodeInfo> q = new ArrayDeque<>();
        q.add(root);
        int visited = 0;
        while (!q.isEmpty() && visited < 1000) {
            AccessibilityNodeInfo n = q.removeFirst();
            visited++;
            if (n == null) continue;
            String pkg = n.getPackageName() == null
                    ? lastForegroundPackage : n.getPackageName().toString();
            if (isEditableNode(n) && signature.equals(nodeSignature(n, pkg))) return n;
            for (int i = 0; i < n.getChildCount(); i++) {
                AccessibilityNodeInfo child = n.getChild(i);
                if (child != null) q.addLast(child);
            }
        }
        return null;
    }

    private WindowManager.LayoutParams overlayParams(int width, int height, int x, int y) {
        WindowManager.LayoutParams lp = new WindowManager.LayoutParams(
                width,
                height,
                WindowManager.LayoutParams.TYPE_ACCESSIBILITY_OVERLAY,
                WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE
                        | WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL
                        | WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN,
                PixelFormat.TRANSLUCENT
        );
        lp.gravity = Gravity.TOP | Gravity.START;
        lp.x = x;
        lp.y = y;
        return lp;
    }

    private int[] menuPositionOutsideField(Rect bounds, int width, int height) {
        int screenW = getResources().getDisplayMetrics().widthPixels;
        int screenH = getResources().getDisplayMetrics().heightPixels;

        // Center the tiny bar horizontally on the edit field when possible.
        int center = bounds.left + bounds.width() / 2;
        int x = center - width / 2;
        x = Math.max(dp(6), Math.min(x, screenW - width - dp(6)));

        // Never cover the input. Prefer above; use below only when there is no room.
        int y = bounds.top - height - dp(5);
        if (y < dp(6)) {
            y = bounds.bottom + dp(5);
        }
        y = Math.max(dp(6), Math.min(y, screenH - height - dp(6)));
        return new int[]{x, y};
    }

    private void hidePasteMenu() {
        handler.removeCallbacks(hideMenusRunnable);
        if (pasteMenu != null && windowManager != null) {
            try {
                windowManager.removeView(pasteMenu);
            } catch (Throwable ignored) {
            }
        }
        pasteMenu = null;
    }

    private void hideHistoryPanel() {
        if (historyHolder != null && historyHolder.view != null && windowManager != null) {
            try {
                windowManager.removeView(historyHolder.view);
            } catch (Throwable ignored) {
            }
        }
        historyHolder = null;
    }

    private void resetTapDetector() {
        lastSignalAt = 0L;
        lastSignalSignature = "";
        firstTapAt = 0L;
        firstTapSignature = "";
    }

    private void incrementPasteCount() {
        SharedPreferences p = getSharedPreferences(MainActivity.PREFS, MODE_PRIVATE);
        long count = p.getLong(MainActivity.KEY_PASTE_COUNT, 0L);
        p.edit().putLong(MainActivity.KEY_PASTE_COUNT, count + 1L).apply();
    }

    private boolean isDoubleTapPasteEnabled() {
        return getSharedPreferences(MainActivity.PREFS, MODE_PRIVATE)
                .getBoolean(MainActivity.KEY_DOUBLE_TAP_PASTE, true);
    }

    private int dp(int value) {
        return Math.round(value * getResources().getDisplayMetrics().density);
    }

    @Override
    public void onInterrupt() {
        hidePasteMenu();
        hideHistoryPanel();
        resetTapDetector();
    }

    @Override
    public void onDestroy() {
        handler.removeCallbacksAndMessages(null);
        hidePasteMenu();
        hideHistoryPanel();
        if (clipboardManager != null) {
            try {
                clipboardManager.removePrimaryClipChangedListener(clipboardListener);
            } catch (Throwable ignored) {
            }
        }
        ShizukuClipboardBridge.stop();
        super.onDestroy();
    }

    private static final class ViewHolder {
        android.view.View view;
    }
}
