package com.mrtien.autoskip;

import android.accessibilityservice.AccessibilityService;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.PixelFormat;
import android.graphics.Rect;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.os.SystemClock;
import android.view.Gravity;
import android.view.WindowManager;
import android.view.accessibility.AccessibilityEvent;
import android.view.accessibility.AccessibilityNodeInfo;
import android.view.accessibility.AccessibilityWindowInfo;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import java.util.ArrayDeque;
import java.util.List;
import java.util.Locale;

/**
 * v2.2.2 passive paste service.
 * Never intercepts touch. Native double-tap/selection always belongs to Android.
 * The tiny overlay stays alive while visible; self-generated WINDOW events cannot
 * immediately close it.
 */
public class PassivePasteAccessibilityService extends AccessibilityService {

    private static final long DOUBLE_MIN = 80L;
    private static final long DOUBLE_MAX = 760L;
    private static final long EVENT_CLUSTER = 105L;
    private static final long TEXT_GUARD = 240L;
    private static final long MENU_TIMEOUT = 8000L;

    private final Handler handler = new Handler(Looper.getMainLooper());
    private WindowManager wm;
    private ClipboardManager clipboard;

    private LinearLayout menu;
    private LinearLayout historyPanel;
    private AccessibilityNodeInfo target;
    private String targetSignature = "";
    private final Rect targetBounds = new Rect();
    private String targetPackage = "";
    private long menuShownAt;

    private long lastTextChangedAt;
    private long lastClusterAt;
    private String lastClusterSignature = "";
    private long firstTapAt;
    private String firstTapSignature = "";

    private String lastSelectedText = "";
    private long lastSelectedAt;

    private final Runnable hideRunnable = this::hideAll;
    private final ClipboardManager.OnPrimaryClipChangedListener clipListener =
            () -> handler.postDelayed(this::captureClipboard, 100L);

    @Override
    protected void onServiceConnected() {
        super.onServiceConnected();
        wm = (WindowManager) getSystemService(WINDOW_SERVICE);
        clipboard = (ClipboardManager) getSystemService(CLIPBOARD_SERVICE);
        if (clipboard != null) {
            try { clipboard.addPrimaryClipChangedListener(clipListener); } catch (Throwable ignored) {}
        }
        if (ShizukuClipboardBridge.hasPermission()) ShizukuClipboardBridge.start(this);
        resetDetector();
    }

    @Override
    public void onAccessibilityEvent(AccessibilityEvent event) {
        if (event == null) return;
        final int type = event.getEventType();
        final String pkg = event.getPackageName() == null ? "" : event.getPackageName().toString();

        if (type == AccessibilityEvent.TYPE_VIEW_TEXT_SELECTION_CHANGED) {
            rememberSelectedText(event.getSource());
        }
        if (type == AccessibilityEvent.TYPE_VIEW_CLICKED) {
            String label = nodeLabel(event.getSource());
            if (isCopyLabel(label)) {
                if (!lastSelectedText.isEmpty()
                        && SystemClock.elapsedRealtime() - lastSelectedAt < 10000L) {
                    ClipboardHistoryStore.addText(this, lastSelectedText);
                }
                handler.postDelayed(this::captureClipboard, 120L);
            }
        }

        if (!enabled()) {
            hideAll();
            resetDetector();
            return;
        }

        // CRITICAL v2.2.2 fix: while our menu is visible, accessibility window/content
        // events generated by adding that overlay must NEVER close the same menu.
        if (menu != null || historyPanel != null) {
            return;
        }

        if (getPackageName().equals(pkg)) return;

        if (type == AccessibilityEvent.TYPE_VIEW_TEXT_CHANGED) {
            lastTextChangedAt = SystemClock.elapsedRealtime();
            resetDetector();
            return;
        }

        if (type == AccessibilityEvent.TYPE_WINDOW_STATE_CHANGED
                || type == AccessibilityEvent.TYPE_WINDOWS_CHANGED) {
            resetDetector();
            return;
        }

        if (type != AccessibilityEvent.TYPE_VIEW_FOCUSED
                && type != AccessibilityEvent.TYPE_VIEW_CLICKED
                && type != AccessibilityEvent.TYPE_VIEW_TEXT_SELECTION_CHANGED) {
            return;
        }

        AccessibilityNodeInfo editable = resolveEditable(event);
        if (!isEditable(editable)) return;
        String epkg = editable.getPackageName() == null ? pkg : editable.getPackageName().toString();
        if (getPackageName().equals(epkg)) return;
        String sig = signature(editable, epkg);

        if (type == AccessibilityEvent.TYPE_VIEW_TEXT_SELECTION_CHANGED) {
            if (SystemClock.elapsedRealtime() - lastTextChangedAt < TEXT_GUARD) return;
            int s = editable.getTextSelectionStart();
            int e = editable.getTextSelectionEnd();
            // Native Android double tap selected a word: preserve native selection and
            // only add our tiny paste pill beside it.
            if (s >= 0 && e >= 0 && s != e) {
                resetDetector();
                showMenu(editable, sig, epkg);
                return;
            }
        }

        registerSignal(editable, sig, epkg);
    }

    private void registerSignal(AccessibilityNodeInfo editable, String sig, String pkg) {
        long now = SystemClock.elapsedRealtime();
        if (sig.equals(lastClusterSignature) && now - lastClusterAt < EVENT_CLUSTER) return;
        lastClusterAt = now;
        lastClusterSignature = sig;

        long dt = now - firstTapAt;
        if (firstTapAt > 0 && sig.equals(firstTapSignature) && dt >= DOUBLE_MIN && dt <= DOUBLE_MAX) {
            resetDetector();
            showMenu(editable, sig, pkg);
        } else {
            firstTapAt = now;
            firstTapSignature = sig;
        }
    }

    private void showMenu(AccessibilityNodeInfo editable, String sig, String pkg) {
        if (wm == null || editable == null) return;
        hideAll();
        captureClipboard();

        try { target = AccessibilityNodeInfo.obtain(editable); }
        catch (Throwable t) { target = editable; }
        targetSignature = sig;
        targetPackage = pkg == null ? "" : pkg;
        editable.getBoundsInScreen(targetBounds);
        if (targetBounds.isEmpty()) return;

        LinearLayout bar = new LinearLayout(this);
        bar.setOrientation(LinearLayout.HORIZONTAL);
        bar.setGravity(Gravity.CENTER);
        bar.setPadding(dp(1), 0, dp(1), 0);
        GradientDrawable bg = new GradientDrawable();
        bg.setColor(Color.rgb(35, 35, 35));
        bg.setCornerRadius(dp(7));
        bar.setBackground(bg);
        bar.setElevation(dp(5));

        TextView paste = item("DÁN", 11f);
        paste.setOnClickListener(v -> pasteLatest());
        bar.addView(paste, new LinearLayout.LayoutParams(dp(38), dp(25)));

        TextView hist = item("▤", 13f);
        hist.setContentDescription("Lịch sử sao chép");
        hist.setOnClickListener(v -> showHistory());
        bar.addView(hist, new LinearLayout.LayoutParams(dp(22), dp(25)));

        int menuW = dp(62), menuH = dp(27);
        int[] pos = position(targetBounds, menuW, menuH);
        WindowManager.LayoutParams lp = overlayParams(
                WindowManager.LayoutParams.WRAP_CONTENT,
                WindowManager.LayoutParams.WRAP_CONTENT,
                pos[0], pos[1]);
        menu = bar;
        menuShownAt = SystemClock.elapsedRealtime();
        try {
            wm.addView(bar, lp);
            handler.removeCallbacks(hideRunnable);
            handler.postDelayed(hideRunnable, MENU_TIMEOUT);
        } catch (Throwable t) {
            menu = null;
        }
    }

    private TextView item(String text, float size) {
        TextView v = new TextView(this);
        v.setText(text);
        v.setTextColor(Color.WHITE);
        v.setTextSize(size);
        v.setGravity(Gravity.CENTER);
        v.setPadding(dp(2), 0, dp(2), 0);
        return v;
    }

    private void pasteLatest() {
        handler.removeCallbacks(hideRunnable);
        boolean ok = pasteToTarget();
        if (ok) incrementCount();
        else Toast.makeText(this, "Không dán được vào ô này.", Toast.LENGTH_SHORT).show();
        hideAll();
        resetDetector();
    }

    private void showHistory() {
        captureClipboard();
        List<ClipboardHistoryStore.Item> items = ClipboardHistoryStore.load(this);
        if (items.isEmpty()) {
            Toast.makeText(this, "Chưa có lịch sử sao chép.", Toast.LENGTH_SHORT).show();
            return;
        }
        hideHistoryOnly();

        LinearLayout root = new LinearLayout(this);
        root.setOrientation(LinearLayout.VERTICAL);
        root.setPadding(dp(6), dp(6), dp(6), dp(6));
        GradientDrawable bg = new GradientDrawable();
        bg.setColor(Color.rgb(40, 40, 40));
        bg.setCornerRadius(dp(12));
        root.setBackground(bg);
        root.setElevation(dp(8));

        TextView title = item("LỊCH SỬ   ✕", 12f);
        title.setGravity(Gravity.START | Gravity.CENTER_VERTICAL);
        title.setOnClickListener(v -> hideHistoryOnly());
        root.addView(title, new LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT, dp(34)));

        ScrollView scroll = new ScrollView(this);
        LinearLayout list = new LinearLayout(this);
        list.setOrientation(LinearLayout.VERTICAL);
        scroll.addView(list);
        int n = Math.min(items.size(), 30);
        for (int i = 0; i < n; i++) {
            ClipboardHistoryStore.Item ci = items.get(i);
            TextView row = item(ci.preview(), 13f);
            row.setGravity(Gravity.START | Gravity.CENTER_VERTICAL);
            row.setPadding(dp(9), dp(8), dp(9), dp(8));
            row.setOnClickListener(v -> pasteHistory(ci));
            list.addView(row, new LinearLayout.LayoutParams(
                    LinearLayout.LayoutParams.MATCH_PARENT,
                    LinearLayout.LayoutParams.WRAP_CONTENT));
        }
        root.addView(scroll, new LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT, dp(240)));

        int sw = getResources().getDisplayMetrics().widthPixels;
        int sh = getResources().getDisplayMetrics().heightPixels;
        int w = Math.min(dp(330), sw - dp(18));
        int h = dp(280);
        int x = Math.max(dp(9), Math.min(targetBounds.left, sw - w - dp(9)));
        int y = targetBounds.top - h - dp(7);
        if (y < dp(8)) y = Math.min(targetBounds.bottom + dp(7), sh - h - dp(8));

        historyPanel = root;
        try {
            wm.addView(root, overlayParams(w, h, x, y));
            handler.removeCallbacks(hideRunnable);
            handler.postDelayed(hideRunnable, 12000L);
        } catch (Throwable t) {
            historyPanel = null;
        }
    }

    private void pasteHistory(ClipboardHistoryStore.Item item) {
        if (clipboard == null) return;
        ClipData cd = ClipboardHistoryStore.toClipData(this, item);
        if (cd == null) return;
        try { clipboard.setPrimaryClip(cd); }
        catch (Throwable t) {
            Toast.makeText(this, "Mục này không còn truy cập được.", Toast.LENGTH_SHORT).show();
            return;
        }
        hideHistoryOnly();
        handler.postDelayed(() -> {
            if (pasteToTarget()) incrementCount();
            else Toast.makeText(this, "Không dán được mục đã chọn.", Toast.LENGTH_SHORT).show();
            hideAll();
        }, 120L);
    }

    private boolean pasteToTarget() {
        AccessibilityNodeInfo node = target;
        if (node == null || !isEditableLoose(node)) node = findBySignature(targetSignature);
        if (node == null) node = findFocusedEditable();
        if (node == null) return false;
        try {
            node.performAction(AccessibilityNodeInfo.ACTION_FOCUS);
            if (node.performAction(AccessibilityNodeInfo.ACTION_PASTE)) return true;
        } catch (Throwable ignored) {}
        return setTextFallback(node);
    }

    private boolean setTextFallback(AccessibilityNodeInfo node) {
        if (clipboard == null || node == null) return false;
        try {
            ClipData cd = clipboard.getPrimaryClip();
            if (cd == null || cd.getItemCount() == 0) return false;
            CharSequence ins = cd.getItemAt(0).coerceToText(this);
            if (ins == null) return false;
            String old = node.getText() == null ? "" : node.getText().toString();
            int s = node.getTextSelectionStart(), e = node.getTextSelectionEnd();
            if (s < 0 || s > old.length()) s = old.length();
            if (e < 0 || e > old.length()) e = s;
            if (e < s) { int t = s; s = e; e = t; }
            String value = old.substring(0, s) + ins + old.substring(e);
            Bundle b = new Bundle();
            b.putCharSequence(AccessibilityNodeInfo.ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE, value);
            return node.performAction(AccessibilityNodeInfo.ACTION_SET_TEXT, b);
        } catch (Throwable ignored) { return false; }
    }

    private AccessibilityNodeInfo resolveEditable(AccessibilityEvent event) {
        AccessibilityNodeInfo n = event.getSource();
        for (int i = 0; n != null && i < 7; i++) {
            if (isEditable(n)) return n;
            n = n.getParent();
        }
        return findFocusedEditable();
    }

    private AccessibilityNodeInfo findFocusedEditable() {
        try {
            List<AccessibilityWindowInfo> ws = getWindows();
            if (ws != null) {
                for (int i = ws.size() - 1; i >= 0; i--) {
                    AccessibilityWindowInfo w = ws.get(i);
                    if (w == null || w.getRoot() == null) continue;
                    AccessibilityNodeInfo n = w.getRoot().findFocus(AccessibilityNodeInfo.FOCUS_INPUT);
                    if (isEditable(n)) return n;
                }
            }
        } catch (Throwable ignored) {}
        try {
            AccessibilityNodeInfo root = getRootInActiveWindow();
            AccessibilityNodeInfo n = root == null ? null : root.findFocus(AccessibilityNodeInfo.FOCUS_INPUT);
            if (isEditable(n)) return n;
        } catch (Throwable ignored) {}
        return null;
    }

    private boolean isEditable(AccessibilityNodeInfo n) {
        if (n == null || !n.isVisibleToUser() || !n.isEnabled() || n.isPassword()) return false;
        if (n.isEditable() && n.isFocused()) return true;
        CharSequence c = n.getClassName();
        if (c != null && n.isFocused()) {
            String s = c.toString().toLowerCase(Locale.ROOT);
            if (s.contains("edittext") || s.contains("textfield") || s.contains("searchview")) return true;
        }
        return false;
    }

    private boolean isEditableLoose(AccessibilityNodeInfo n) {
        if (n == null || !n.isVisibleToUser() || !n.isEnabled() || n.isPassword()) return false;
        if (n.isEditable()) return true;
        CharSequence c = n.getClassName();
        if (c != null) {
            String s = c.toString().toLowerCase(Locale.ROOT);
            return s.contains("edittext") || s.contains("textfield") || s.contains("searchview");
        }
        return false;
    }

    private String signature(AccessibilityNodeInfo n, String pkg) {
        Rect r = new Rect(); n.getBoundsInScreen(r);
        String id = n.getViewIdResourceName();
        String cls = n.getClassName() == null ? "" : n.getClassName().toString();
        return pkg + "|" + (id == null ? "" : id) + "|" + cls + "|" + r.flattenToString();
    }

    private AccessibilityNodeInfo findBySignature(String sig) {
        if (sig == null || sig.isEmpty()) return null;
        try {
            List<AccessibilityWindowInfo> ws = getWindows();
            if (ws != null) for (AccessibilityWindowInfo w : ws) {
                if (w == null) continue;
                AccessibilityNodeInfo f = bfs(w.getRoot(), sig);
                if (f != null) return f;
            }
        } catch (Throwable ignored) {}
        return bfs(getRootInActiveWindow(), sig);
    }

    private AccessibilityNodeInfo bfs(AccessibilityNodeInfo root, String sig) {
        if (root == null) return null;
        ArrayDeque<AccessibilityNodeInfo> q = new ArrayDeque<>(); q.add(root);
        int seen = 0;
        while (!q.isEmpty() && seen++ < 1000) {
            AccessibilityNodeInfo n = q.removeFirst();
            String pkg = n.getPackageName() == null ? targetPackage : n.getPackageName().toString();
            if (isEditableLoose(n) && sig.equals(signature(n, pkg))) return n;
            for (int i = 0; i < n.getChildCount(); i++) {
                AccessibilityNodeInfo c = n.getChild(i); if (c != null) q.addLast(c);
            }
        }
        return null;
    }

    private int[] position(Rect b, int w, int h) {
        int sw = getResources().getDisplayMetrics().widthPixels;
        int sh = getResources().getDisplayMetrics().heightPixels;
        int x = Math.max(dp(5), Math.min(b.right - w, sw - w - dp(5)));
        int y = b.top - h - dp(4);
        if (y < dp(4)) y = Math.min(b.bottom + dp(4), sh - h - dp(4));
        return new int[]{x, y};
    }

    private WindowManager.LayoutParams overlayParams(int w, int h, int x, int y) {
        WindowManager.LayoutParams lp = new WindowManager.LayoutParams(
                w, h, WindowManager.LayoutParams.TYPE_ACCESSIBILITY_OVERLAY,
                WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE
                        | WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL
                        | WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN,
                PixelFormat.TRANSLUCENT);
        lp.gravity = Gravity.TOP | Gravity.START;
        lp.x = x; lp.y = y;
        return lp;
    }

    private void captureClipboard() {
        ClipData cd = null;
        if (ShizukuClipboardBridge.hasPermission()) {
            if (!ShizukuClipboardBridge.isRunning()) ShizukuClipboardBridge.start(this);
            cd = ShizukuClipboardBridge.readNow();
        }
        if (cd == null && clipboard != null) {
            try { cd = clipboard.getPrimaryClip(); } catch (Throwable ignored) {}
        }
        if (cd != null) ClipboardHistoryStore.addClip(this, cd);
    }

    private void rememberSelectedText(AccessibilityNodeInfo n) {
        if (n == null || n.getText() == null) return;
        try {
            int s = n.getTextSelectionStart(), e = n.getTextSelectionEnd();
            String t = n.getText().toString();
            if (s >= 0 && e > s && e <= t.length()) {
                lastSelectedText = t.substring(s, e);
                lastSelectedAt = SystemClock.elapsedRealtime();
            }
        } catch (Throwable ignored) {}
    }

    private String nodeLabel(AccessibilityNodeInfo n) {
        if (n == null) return "";
        CharSequence c = n.getText();
        if (c == null || c.length() == 0) c = n.getContentDescription();
        return c == null ? "" : c.toString().trim().toLowerCase(Locale.ROOT);
    }

    private boolean isCopyLabel(String s) {
        return "copy".equals(s) || "sao chép".equals(s) || "sao chep".equals(s);
    }

    private void hideAll() {
        handler.removeCallbacks(hideRunnable);
        if (menu != null && wm != null) try { wm.removeView(menu); } catch (Throwable ignored) {}
        if (historyPanel != null && wm != null) try { wm.removeView(historyPanel); } catch (Throwable ignored) {}
        menu = null; historyPanel = null;
    }

    private void hideHistoryOnly() {
        if (historyPanel != null && wm != null) try { wm.removeView(historyPanel); } catch (Throwable ignored) {}
        historyPanel = null;
    }

    private void resetDetector() {
        lastClusterAt = 0L; lastClusterSignature = "";
        firstTapAt = 0L; firstTapSignature = "";
    }

    private boolean enabled() {
        return getSharedPreferences(MainActivity.PREFS, MODE_PRIVATE)
                .getBoolean(MainActivity.KEY_DOUBLE_TAP_PASTE, true);
    }

    private void incrementCount() {
        SharedPreferences p = getSharedPreferences(MainActivity.PREFS, MODE_PRIVATE);
        long c = p.getLong(MainActivity.KEY_PASTE_COUNT, 0L);
        p.edit().putLong(MainActivity.KEY_PASTE_COUNT, c + 1L).apply();
    }

    private int dp(int v) { return Math.round(v * getResources().getDisplayMetrics().density); }

    @Override public void onInterrupt() { hideAll(); }

    @Override
    public void onDestroy() {
        handler.removeCallbacksAndMessages(null);
        hideAll();
        if (clipboard != null) try { clipboard.removePrimaryClipChangedListener(clipListener); } catch (Throwable ignored) {}
        ShizukuClipboardBridge.stop();
        super.onDestroy();
    }
}
